name: virtual_lab
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  flutter_screenutil: ^5.9.3
  riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  audioplayers: ^6.4.0
  get: ^4.7.2
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  http: ^1.4.0
  cloudinary_url_gen: ^1.7.0
  cloudinary: ^1.2.0
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  cloudinary_flutter: ^1.3.0
  flutter_animate: ^4.5.2
  package_info_plus: ^8.3.0
  quickalert: ^1.1.0
  http_parser: ^4.1.2
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/effects/
    - assets/icons/
    - assets/fonts/
    - assets/logo/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/logo.png
  android: true
  ios: true
  web: false
