import 'package:virtual_lab/models/ingredients_model.dart';



List<IngredientsModel> ingredientJson = [
  IngredientsModel(
    tags: ['coc1'],
    name: 'chicken',
    category: 'meat',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752288722/chicken_s62zgp.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'fish',
    category: 'meat',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752288722/fish_gfxg1l.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'tofu',
    category: 'meat',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752288722/tofu_aihuwd.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'cabbage',
    category: 'vegetable',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752288722/cabbage_fd0qag.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'carrot',
    category: 'vegetable',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752288722/carrot_prj0im.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'potato',
    category: 'vegetable',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752288723/potato_s7xpzg.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'onion',
    category: 'vegetable',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752288722/onion_f3imjj.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'garlic',
    category: 'vegetable',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752288722/garlic_mvaunp.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'rice',
    category: 'grain',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752409828/rice_wwcorg.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1', 'coc2'],
    name: 'bread',
    category: 'grain',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752288722/bread_jdixpz.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'salt',
    category: 'grain',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612124/salt_zklonn.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1', 'coc2'],
    name: 'bell pepper',
    category: 'spice',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752288722/pepper_ycsowv.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'soy sauce',
    category: 'spice',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752325724/soy_sauce_zq2ep0.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'cooking oil',
    category: 'spice',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1752288722/oil_nkxoqu.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'vinegar',
    category: 'spice',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612871/vinegar_gis45c.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1', 'coc2'],
    name: 'sugar',
    category: 'spice',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753613141/sugar_d98inb.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'tomato paste',
    category: 'spice',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612870/tomato_paste_hifcjx.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1', 'coc2'],
    name: 'chili flakes',
    category: 'spice',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612871/chili_plakes_xay7zr.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1', 'coc2'],
    name: 'ginger',
    category: 'vegetable',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612869/ginger_d70f1j.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1', 'coc2'],
    name: 'butter',
    category: 'dairy',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612871/butter_ioltgx.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1', 'coc2'],
    name: 'cornstarch',
    category: 'grain',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612869/cornstarch_nociat.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1', 'coc2'],
    name: 'beef',
    category: 'meat',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612872/beef_qcitkg.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1', 'coc2'],
    name: 'pork',
    category: 'meat',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612870/pork_bfkags.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'egg',
    category: 'dairy',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612869/egg_oqccce.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1', 'coc2'],
    name: 'mushroom',
    category: 'vegetable',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612869/mushrom_ccdtel.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'noodles',
    category: 'grain',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612870/noodles_anljps.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc1'],
    name: 'flour',
    category: 'grain',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1753612869/flour_g3dt1n.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),



  //? NEW
  IngredientsModel(
    tags: ['coc2'],
    name: 'lettuce',
    category: 'vegetable',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1755781939/lettus_qcm7yg.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc2'],
    name: 'tomato',
    category: 'vegetable',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1755781940/tomato_rumbyp.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc2'],
    name: 'rice',
    category: 'grain',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1755781939/rice_dnbcvk.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc2'],
    name: 'mayonnaise',
    category: 'dairy',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1755781939/mayonnaise_o6olby.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc2'],
    name: 'cheese',
    category: 'dairy',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1755781940/cheese_r8xb3h.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc2'],
    name: 'olives',
    category: 'vegetable',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1755781939/olives_zncazn.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc2'],
    name: 'avocado',
    category: 'vegetable',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1755781939/avocado_udkvxi.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc2'],
    name: 'mustard',
    category: 'spice',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1755781940/mustard_pebdcy.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc2'],
    name: 'parsley',
    category: 'spice',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1755781939/parsley_ra4peb.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  IngredientsModel(
    tags: ['coc2'],
    name: 'lemon',
    category: 'vegetable',
    image: 'https://res.cloudinary.com/dgvi2di6t/image/upload/v1755781940/lemon_czovhy.png',
    actions: [ActionsModel(action: '', status: '', tool: '')],
  ),
  
];
