enum IngredientType {vegetable, meat, fruit, grain, dairy, spice}
enum ActionStatus {perfect, good, bad}

enum ActionType {  
  chop,    
  peel,    
  stir,    
  cut,     
  marinate,
  slice,   
  blend,   
  grind,   
  pour,    
  grate,   
  sprinkle,
  rinse,   
  soak,    
  season,  
  whisk,   
  crack,   
  beat,    
  wash,    
  scoop,   
  scramble,
  clean
}

enum ToolType {
  knife,        
  chopper,      
  cleaver,      
  peeler,       
  paringKnife,  
  spoon,        
  spatula,      
  whisk,        
  scissors,     
  cutter,       
  container,    
  tongs,        
  blender,      
  foodProcessor,
  grinder,      
  mortarAndPestle,
  mill,         
  pitcher,      
  ladle,        
  grater,       
  strainer,     
  sink,         
  shaker,       
  hand,         
  fork,         
  mixer,   
  measuringCup, 
  mandolineSlicer, 
  ziplocBag, 
  cup,  
  bowl,
  zester,
  breadSlicer
}
